### ISSUE TITLE
Conflict with GVM (Groovy enVironment Manager)

### ISSUE THREAD

**Issue by TheKojuEffect** [moovweb/gvm#103]
I had installed [GVM (Groovy enVironment Manager) ](http://gvmtool.net/) in my Ubuntu system.

When I try to install gvm with

 `bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)`, 

I get `ERROR: Already installed!`.

Is there anyway to install gvm without conflicting with GVM?

**Comment by kyleboon** [comment]
I renamed the function via a bash function so that I don't need to modify the source. http://kyleboon.org/blog/2015/02/23/groovy-gvm-and-go-gvm/

**Comment by henyojess** [comment]
how abouts changing to govm instead of gvm ;)

**Comment by wldcordeiro** [comment]
+1 the idea of govm over gvm @henyojess

**Comment by VitorFreitas** [comment]
+1 the idea of govm over gvm @wldcordeiro.

**Comment by chlam4** [comment]
+1 the idea of govm over gvm @henyojess

**Comment by wldcordeiro** [comment]
No longer needed because Groovy enVironment Manager became SDK.

**Comment by TheKojuEffect** [comment]
Closing this ticket as Groovy enVironment Manager is now SDKMAN.

**Comment by leighmcculloch** [comment]
This is actually still a problem because SDKMAN hijacks the `gvm` command. Even if you install `gvm` after `sdk`, `gvm` is still aliased to `sdk` for some reason.

**Comment by techgaun** [comment]
Had the same problem as @leighmcculloch and got rid of sdkman as I am no longer writing groovy. Found this line on sdkman : https://github.com/sdkman/sdkman-cli/blob/master/src/main/bash/sdkman-init.sh#L173-L175

Maybe a PR should be done to reverse that on their end so that aliasing to `gvm` is actually not a default.

Anyway, I personally still prefer if the name was govm but maybe thats just me. The project works great otherwise. Thanks!

**Comment by techgaun** [comment]
I did a PR yesterday to sdkman to get rid of gvm alias all together and now there should be no conflict anymore.

**Comment by leighmcculloch** [comment]
@techgaun's PR was merged. sdkman/sdkman-cli#608
