### ISSUE TITLE
The name conflicts with Groovy's gvm.

### ISSUE THREAD

**Issue by kt3k** [moovweb/gvm#82]
Hi,

How do you think about the name conflict with Groovy's `gvm`? Recently I'm interested in this tool but I'm also very dependent on Groovy's `gvm` (especially in JVM-releated development like android app or gradle plugin), so I cannot try it...

**Comment by agentgt** [comment]
Not that I care that much about who changes the name of their dot directory and bin but IMO gvm should have been named govm a long time to be consistent with go's other tool names (gofmt, gocode etc).

To make this situation even more confusing is that their is a new project called govm. I'm not quite sure why it exists since it seems to do the exact same thing as gvm.

**Comment by jayanmn** [comment]
GVM is superceded by http://sdkman.io/.  `gvm` command became `sdk`
